all-pdf:
    #!/usr/bin/env bash
    shopt -s nullglob
    set -eu
    for file in */*.typ; do
        just make-pdf "$file"
    done

make-pdf filename:
    typst c --root=.. {{filename}} pdf/{{parent_directory(filename)}}.pdf

test:
    tt run --root=.. -j8
    
clean:
    #!/usr/bin/env bash
    rm -r */.ipynb_checkpoints
