default: export execute
    
export:
    typst query --root=../.. --input callisto-export=true --pretty --one --field=value test.typ '<notebook>' > export.ipynb
    typst query --root=../.. --input callisto-export=julia --pretty --one --field=value test.typ '<julia>' > export-julia.ipynb

execute:
    jupyter-nbconvert --to notebook --execute --inplace export.ipynb
    jupyter-nbconvert --to notebook --execute --inplace export-julia.ipynb

watch:
    watchexec -w . -f '**/*.typ' just export execute
    
